### PR TITLE
feat: added RichText component

### PR DESCRIPTION
**Pull request by RosaIsela31**
Changes: added RichText component

### CODE REVIEW

**Review by melscastillo — APPROVED** [review]
Don't forget to import this component in the main js when conflicts are resolve. 
LGFM :rocket:

**Comment by omero** [comment]
@melscastillo
>Don't forget to import this component in the main js when conflicts are resolve.

That import is part of the scope of this ticket? or is something we should do in this one

**Comment by melscastillo** [comment]
> @melscastillo
> 
> > Don't forget to import this component in the main js when conflicts are resolve.
> 
> That import is part of the scope of this ticket? or is something we should do in this one

Is something we can resolve in another future ticket

**Review by georch — APPROVED** [review]
LGTM

**Pull request merged**
